language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SILEX_VERSION=1.2.*
  - SILEX_VERSION=1.1.*
  - SILEX_VERSION=1.0.*

before_script:
  - php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"
  - php composer.phar require --dev --no-interaction --prefer-dist silex/silex:${SILEX_VERSION}

script:
    - mkdir -p build/logs
    - composer test -- --coverage-text --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

notifications:
  email:
    - mudi@renegare.com

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
